version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
    ports:
      - "4200:80"
