INSERT INTO boatDb.app_user (
    email,
    first_name,
    last_name,
    password,
    role,
    created_by,
    created_date,
    last_modified_by,
    last_modified_date
) VALUES
    ('admin@test.com', 'admin', 'admin', '$2a$10$MU2Ene90yUfYWYevRb6AcObfht3z8.tmfcco0dj0e6MAbTiKoYZiK', 'ROLE_ADMIN', 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('user@test.com', 'user', 'user', '$2a$10$MU2Ene90yUfYWYevRb6AcObfht3z8.tmfcco0dj0e6MAbTiKoYZiK', 'ROLE_USER', 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199');

INSERT INTO boatDb.boat (name, description, image_url, user_id, created_by, created_date, last_modified_by, last_modified_date)
VALUES
    ('Sea Breeze', 'A luxury yacht for private cruises', 'assets/img/pexels-blitzboy-1106423.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Ocean Whisper', 'Fishing boat with sonar and radar', 'assets/img/pexels-frans-van-heerden-201846-625418.jpg', 1, 'admin', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Coral Voyager', 'Tour boat for exploring coral reefs', 'assets/img/pexels-goumbik-296278.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Wave Rider', 'Speedboat designed for thrill rides', 'assets/img/pexels-hakantahmaz-2536643.jpg', 2, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Blue Horizon', 'Sailboat for open ocean expeditions', 'assets/img/pexels-korhan-erdol-1123380-2344572.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Storm Chaser', 'Rescue boat used in extreme weather', 'assets/img/pexels-lecreusois-240561.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Sunny Skipper', 'Small family boat for leisure', 'assets/img/pexels-mali-42092.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Aqua Dancer', 'Recreational boat for lakes and rivers', 'assets/img/pexels-md-towhidul-islam-175863-3013018.jpg', 1, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Pelican Glide', 'Boat used for bird-watching tours', 'assets/img/pexels-minan1398-715567.jpg', 2, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199'),
    ('Neptune’s Pride', 'Historic replica used for events', 'assets/img/pexels-nuno-obey-34504-128302.jpg', 2, 'system', '2025-05-26 12:57:34.41199', NULL, '2025-05-26 12:57:34.41199');

INSERT INTO boatDb.message (code, fr, en) VALUES
    ('USER_AUTH.REGISTER_SUCCESS', 'Utilisateur enregistré avec succès', 'User registered successfully'),
    ('USER_AUTH.REGISTER_EMAIL_TAKEN', 'L''adresse e-mail est déjà utilisée', 'Email is already taken'),
    ('USER_AUTH.LOGIN_SUCCESS', 'Connexion réussie', 'User login successfully'),
    ('USER_AUTH.LOGIN_USER_NOT_FOUND', 'Utilisateur non trouvé', 'User not found'),
    ('USER_AUTH.LOGIN_FAILED', 'Échec de la connexion', 'Failed to login'),
    ('SELECT_LANGUAGE', 'Sélectionnez la langue', 'Select Language'),
    ('COMMON.UNKNOWN', 'Une erreur inconnue est survenue, veuillez contacter l''administrateur.','An unknown error occurred, please contact the administrator.'),
    ('COMMON.BACK', 'Retour', 'Back'),
    ('COMMON.OWNER', 'Créer par', 'Created By'),
    ('COMMON.YES', 'Oui', 'Yes'),
    ('COMMON.CANCEL', 'Annuler', 'Cancel'),
    ('COMMON.CONFIRM_MESSAGE', 'Êtes-vous sûr de vouloir supprimer ce bateau?', 'Are you sure you want to delete this boat?'),
    ('COMMON.ACCESS_DENIED', 'Accès refusé', 'Access Denied'),
    ('COMMON.ACCESS_DENIED_INFO', 'Vous n''avez pas la permission d''accéder à cette page', 'You do not have permission to view this page'),
    ('NAVBAR.BRAND', 'BoatBooK', 'BoatBooK'),
    ('NAVBAR.LOGIN', 'Connexion', 'Login'),
    ('NAVBAR.SIGN_UP', 'S''inscrire', 'Sign Up'),
    ('NAVBAR.DASHBOARD', 'Tableau de bord', 'Dashboard'),
    ('NAVBAR.LOGOUT_TOOLTIP', 'Déconnexion', 'Logout'),
    ('LOGIN_PAGE.TITLE', 'Connexion', 'Login'),
    ('LOGIN_PAGE.EMAIL_LABEL', 'Adresse e-mail', 'Email'),
    ('LOGIN_PAGE.PASSWORD_LABEL', 'Mot de passe', 'Password'),
    ('LOGIN_PAGE.LOGIN_BUTTON', 'Se connecter', 'Login'),
    ('LOGIN_PAGE.REMEMBER_ME_LABEL', 'Se souvenir de moi', 'Remember me'),

    ('REGISTER_PAGE.TITLE', 'S''inscrire', 'Register'),
    ('REGISTER_PAGE.ROLE_LABEL', 'Je suis un(e) ', 'I am a '),
    ('REGISTER_PAGE.ROLE_ADMIN', 'Administrateur', 'Admin'),
    ('REGISTER_PAGE.ROLE_USER', 'Utilisateur', 'User'),
    ('REGISTER_PAGE.FIRST_NAME_LABEL', 'Prénom', 'Firstname'),
    ('REGISTER_PAGE.LAST_NAME_LABEL', 'Nom de famille', 'Lastname'),
    ('REGISTER_PAGE.EMAIL_LABEL', 'Adresse e-mail', 'Email'),
    ('REGISTER_PAGE.PASSWORD_LABEL', 'Mot de passe', 'Password'),
    ('REGISTER_PAGE.CONFIRM_PASSWORD_LABEL', 'Confirmer le mot de passe', 'Confirm password'),

    ('REGISTER_PAGE.REGISTER_BUTTON', 'S''inscrire', 'Register'),
    ('REGISTER_PAGE.ERROR_ALL_FIELDS', 'Veuillez remplir tous les champs obligatoires.', 'Please fill in all required fields.'),
    ('HOME_PAGE.HERO_TITLE', 'Découvrez Notre Sélection de Bateaux', 'Discover Our Boat Selection'),
    ('HOME_PAGE.HERO_SUBTITLE', 'Rejoignez une communauté passionnée où les amateurs de bateaux exposent leurs plus belles embarcations. Partagez des moments inoubliables et profitez du plaisir nautique entre passionnés.', 'Join a passionate community where boat enthusiasts showcase their finest vessels. Share unforgettable moments and enjoy nautical fun together with fellow lovers of the sea.'),
    ('HOME_PAGE.HERO_BUTTON_GET_STARTED', 'Voir la gallerie', 'See gallery'),
    ('HOME_PAGE.BOATS_TITLE', 'Gallerie des Bateaux', 'Boats Gallery'),
    ('HOME_PAGE.CLOSE_DETAIL', 'Fermer', 'Close'),
    ('HOME_PAGE.CONFIRM_DELETE', 'Êtes-vous sûr de vouloir supprimer ce bateau?', 'Are you sure you want to delete this boat?'),
    ('DASHBOARD.STATS_TOTAL_USER', 'Nombre d''utilisateurs', 'Number of users'),
    ('DASHBOARD.STATS_TOTAL_BOAT', 'Nombre de bateaux', 'Number of boats'),
    ('DASHBOARD.ALL_BOATS', 'Gérer Tous les bateaux', 'Manage all boats'),
    ('DASHBOARD.MY_BOATS', 'Gérer mes bateaux', 'Manage my boats'),
    ('DASHBOARD.NEW_BOAT', 'Créer nouveau bateau', 'Create new boat'),
    ('DASHBOARD.BOAT_LIST', 'Liste des bateaux', 'Boat list'),
    ('DASHBOARD.SHOW_MINE', 'Voir que mes bateaux', 'Show only my boats'),
    ('ADMIN_PROFILE_PAGE.PROFILE_IMAGE_ALT', 'Profil', 'Profile'),
    ('ADMIN_PROFILE_PAGE.ROLE', 'Rôle', 'Role'),
    ('ADMIN_PROFILE_PAGE.CONTACT_INFO_TITLE', 'Informations de Contact', 'Contact Information'),
    ('FOOTER_TEXT_1', 'Coder par', 'Made with'),
    ('FOOTER_TEXT_MOBILE_1', 'Coder par', 'Coded by'),
    ('FOOTER_TEXT_2', 'en Suisse par', 'in Switzerland by'),
    ('FOOTER_TEXT_3', 'Ahmed Hachmi', 'Ahmed Hachmi'),
    ('BOAT_DETAIL.DELETE', 'Supprimer', 'Delete'),
    ('BOAT_DETAIL.EDIT', 'Editer', 'Edit'),
    ('BOAT_DETAIL.SAVE', 'Enregistrer', 'Save'),
    ('BOAT_DETAIL.NAME', 'Nom', 'Name'),
    ('BOAT_DETAIL.DESCRIPTION', 'Description', 'Description'),
    ('BOAT_DETAIL.IMAGE_URL', 'Image', 'Image'),
    ('API_BOAT.CREATED_SUCCESS', 'Bateau enregistré', 'Boat saved successfully'),
    ('API_BOAT.DELETED', 'Bateau supprimé', 'Boat deleted successfully'),

    ('VALIDATION.BOAT_NAME', 'Nom  invalide, Max 50 caractères', 'Invalid Name, Max 50 caracters'),
    ('VALIDATION.BOAT_DESCRIPTION', 'Description  invalide, Max 300 caractères', 'Invalid Description, Max 300 caracters'),
    ('VALIDATION.BOAT_IMAGE_URL', 'Url de l''image  invalide, Max 200 caractères', 'Invalid Image Url, Max 200 caracters'),

    ('VALIDATION.PASSWORD_FORMAT', 'Le mot de passe doit contenir au moins 8 caractères, une lettre majuscule, un chiffre et un caractère spécial.', 'Password must be at least 8 characters long and include at least one uppercase letter, one number, and one special character.'),
    ('VALIDATION.EMAIL_FORMAT', 'Format de l''E-mail est invalide', 'Invalid Email format'),
    ('VALIDATION.PASSWORD_MISMATCH', 'Les mots de passe ne sont pas identiques', 'Password mismatch'),
    ('VALIDATION.REQUIRED', 'Obligatoire', 'Required'),
    ('VALIDATION.MAX_LENGTH', 'Maximum {{max}} caractères', 'Maximum {{max}} caracters'),
    ('VALIDATION.MIN_LENGTH', 'Minimum {{min}} caractères', 'Minimum {{min}} caracters');



